package com.lbins.meetlove.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lbins.meetlove.dao.Emp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EMP.
*/
public class EmpDao extends AbstractDao<Emp, String> {

    public static final String TABLENAME = "EMP";

    /**
     * Properties of entity Emp.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Empid = new Property(0, String.class, "empid", true, "EMPID");
        public final static Property Mobile = new Property(1, String.class, "mobile", false, "MOBILE");
        public final static Property Password = new Property(2, String.class, "password", false, "PASSWORD");
        public final static Property Nickname = new Property(3, String.class, "nickname", false, "NICKNAME");
        public final static Property Cover = new Property(4, String.class, "cover", false, "COVER");
        public final static Property Sign = new Property(5, String.class, "sign", false, "SIGN");
        public final static Property Age = new Property(6, String.class, "age", false, "AGE");
        public final static Property Sex = new Property(7, String.class, "sex", false, "SEX");
        public final static Property Heightl = new Property(8, String.class, "heightl", false, "HEIGHTL");
        public final static Property Education = new Property(9, String.class, "education", false, "EDUCATION");
        public final static Property Provinceid = new Property(10, String.class, "provinceid", false, "PROVINCEID");
        public final static Property Cityid = new Property(11, String.class, "cityid", false, "CITYID");
        public final static Property Areaid = new Property(12, String.class, "areaid", false, "AREAID");
        public final static Property Marriage = new Property(13, String.class, "marriage", false, "MARRIAGE");
        public final static Property Company = new Property(14, String.class, "company", false, "COMPANY");
        public final static Property Likeids = new Property(15, String.class, "likeids", false, "LIKEIDS");
        public final static Property State = new Property(16, String.class, "state", false, "STATE");
        public final static Property Cardpic = new Property(17, String.class, "cardpic", false, "CARDPIC");
        public final static Property Rzstate1 = new Property(18, String.class, "rzstate1", false, "RZSTATE1");
        public final static Property Rzstate2 = new Property(19, String.class, "rzstate2", false, "RZSTATE2");
        public final static Property Rzstate3 = new Property(20, String.class, "rzstate3", false, "RZSTATE3");
        public final static Property Is_use = new Property(21, String.class, "is_use", false, "IS_USE");
        public final static Property Dateline = new Property(22, String.class, "dateline", false, "DATELINE");
        public final static Property UserId = new Property(23, String.class, "userId", false, "USER_ID");
        public final static Property ChannelId = new Property(24, String.class, "channelId", false, "CHANNEL_ID");
        public final static Property DeviceType = new Property(25, String.class, "deviceType", false, "DEVICE_TYPE");
        public final static Property Chooseid = new Property(26, String.class, "chooseid", false, "CHOOSEID");
        public final static Property Agestart = new Property(27, String.class, "agestart", false, "AGESTART");
        public final static Property Ageend = new Property(28, String.class, "ageend", false, "AGEEND");
        public final static Property Heightlstart = new Property(29, String.class, "heightlstart", false, "HEIGHTLSTART");
        public final static Property Heightlend = new Property(30, String.class, "heightlend", false, "HEIGHTLEND");
        public final static Property Educationm = new Property(31, String.class, "educationm", false, "EDUCATIONM");
        public final static Property Marriagem = new Property(32, String.class, "marriagem", false, "MARRIAGEM");
        public final static Property Pname = new Property(33, String.class, "pname", false, "PNAME");
        public final static Property CityName = new Property(34, String.class, "cityName", false, "CITY_NAME");
        public final static Property Is_push = new Property(35, String.class, "is_push", false, "IS_PUSH");
    };

    private DaoSession daoSession;


    public EmpDao(DaoConfig config) {
        super(config);
    }
    
    public EmpDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EMP' (" + //
                "'EMPID' TEXT PRIMARY KEY NOT NULL ," + // 0: empid
                "'MOBILE' TEXT," + // 1: mobile
                "'PASSWORD' TEXT," + // 2: password
                "'NICKNAME' TEXT," + // 3: nickname
                "'COVER' TEXT," + // 4: cover
                "'SIGN' TEXT," + // 5: sign
                "'AGE' TEXT," + // 6: age
                "'SEX' TEXT," + // 7: sex
                "'HEIGHTL' TEXT," + // 8: heightl
                "'EDUCATION' TEXT," + // 9: education
                "'PROVINCEID' TEXT," + // 10: provinceid
                "'CITYID' TEXT," + // 11: cityid
                "'AREAID' TEXT," + // 12: areaid
                "'MARRIAGE' TEXT," + // 13: marriage
                "'COMPANY' TEXT," + // 14: company
                "'LIKEIDS' TEXT," + // 15: likeids
                "'STATE' TEXT," + // 16: state
                "'CARDPIC' TEXT," + // 17: cardpic
                "'RZSTATE1' TEXT," + // 18: rzstate1
                "'RZSTATE2' TEXT," + // 19: rzstate2
                "'RZSTATE3' TEXT," + // 20: rzstate3
                "'IS_USE' TEXT," + // 21: is_use
                "'DATELINE' TEXT," + // 22: dateline
                "'USER_ID' TEXT," + // 23: userId
                "'CHANNEL_ID' TEXT," + // 24: channelId
                "'DEVICE_TYPE' TEXT," + // 25: deviceType
                "'CHOOSEID' TEXT," + // 26: chooseid
                "'AGESTART' TEXT," + // 27: agestart
                "'AGEEND' TEXT," + // 28: ageend
                "'HEIGHTLSTART' TEXT," + // 29: heightlstart
                "'HEIGHTLEND' TEXT," + // 30: heightlend
                "'EDUCATIONM' TEXT," + // 31: educationm
                "'MARRIAGEM' TEXT," + // 32: marriagem
                "'PNAME' TEXT," + // 33: pname
                "'CITY_NAME' TEXT," + // 34: cityName
                "'IS_PUSH' TEXT);"); // 35: is_push
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EMP'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Emp entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getEmpid());
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(2, mobile);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(3, password);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(4, nickname);
        }
 
        String cover = entity.getCover();
        if (cover != null) {
            stmt.bindString(5, cover);
        }
 
        String sign = entity.getSign();
        if (sign != null) {
            stmt.bindString(6, sign);
        }
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(7, age);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(8, sex);
        }
 
        String heightl = entity.getHeightl();
        if (heightl != null) {
            stmt.bindString(9, heightl);
        }
 
        String education = entity.getEducation();
        if (education != null) {
            stmt.bindString(10, education);
        }
 
        String provinceid = entity.getProvinceid();
        if (provinceid != null) {
            stmt.bindString(11, provinceid);
        }
 
        String cityid = entity.getCityid();
        if (cityid != null) {
            stmt.bindString(12, cityid);
        }
 
        String areaid = entity.getAreaid();
        if (areaid != null) {
            stmt.bindString(13, areaid);
        }
 
        String marriage = entity.getMarriage();
        if (marriage != null) {
            stmt.bindString(14, marriage);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(15, company);
        }
 
        String likeids = entity.getLikeids();
        if (likeids != null) {
            stmt.bindString(16, likeids);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(17, state);
        }
 
        String cardpic = entity.getCardpic();
        if (cardpic != null) {
            stmt.bindString(18, cardpic);
        }
 
        String rzstate1 = entity.getRzstate1();
        if (rzstate1 != null) {
            stmt.bindString(19, rzstate1);
        }
 
        String rzstate2 = entity.getRzstate2();
        if (rzstate2 != null) {
            stmt.bindString(20, rzstate2);
        }
 
        String rzstate3 = entity.getRzstate3();
        if (rzstate3 != null) {
            stmt.bindString(21, rzstate3);
        }
 
        String is_use = entity.getIs_use();
        if (is_use != null) {
            stmt.bindString(22, is_use);
        }
 
        String dateline = entity.getDateline();
        if (dateline != null) {
            stmt.bindString(23, dateline);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(24, userId);
        }
 
        String channelId = entity.getChannelId();
        if (channelId != null) {
            stmt.bindString(25, channelId);
        }
 
        String deviceType = entity.getDeviceType();
        if (deviceType != null) {
            stmt.bindString(26, deviceType);
        }
 
        String chooseid = entity.getChooseid();
        if (chooseid != null) {
            stmt.bindString(27, chooseid);
        }
 
        String agestart = entity.getAgestart();
        if (agestart != null) {
            stmt.bindString(28, agestart);
        }
 
        String ageend = entity.getAgeend();
        if (ageend != null) {
            stmt.bindString(29, ageend);
        }
 
        String heightlstart = entity.getHeightlstart();
        if (heightlstart != null) {
            stmt.bindString(30, heightlstart);
        }
 
        String heightlend = entity.getHeightlend();
        if (heightlend != null) {
            stmt.bindString(31, heightlend);
        }
 
        String educationm = entity.getEducationm();
        if (educationm != null) {
            stmt.bindString(32, educationm);
        }
 
        String marriagem = entity.getMarriagem();
        if (marriagem != null) {
            stmt.bindString(33, marriagem);
        }
 
        String pname = entity.getPname();
        if (pname != null) {
            stmt.bindString(34, pname);
        }
 
        String cityName = entity.getCityName();
        if (cityName != null) {
            stmt.bindString(35, cityName);
        }
 
        String is_push = entity.getIs_push();
        if (is_push != null) {
            stmt.bindString(36, is_push);
        }
    }

    @Override
    protected void attachEntity(Emp entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Emp readEntity(Cursor cursor, int offset) {
        Emp entity = new Emp( //
            cursor.getString(offset + 0), // empid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mobile
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // password
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // nickname
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // cover
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sign
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // age
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // sex
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // heightl
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // education
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // provinceid
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // cityid
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // areaid
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // marriage
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // company
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // likeids
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // state
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // cardpic
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // rzstate1
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // rzstate2
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // rzstate3
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // is_use
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // dateline
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // userId
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // channelId
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // deviceType
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // chooseid
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // agestart
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // ageend
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // heightlstart
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // heightlend
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // educationm
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // marriagem
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // pname
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // cityName
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35) // is_push
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Emp entity, int offset) {
        entity.setEmpid(cursor.getString(offset + 0));
        entity.setMobile(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPassword(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNickname(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCover(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSign(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAge(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSex(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHeightl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEducation(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setProvinceid(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCityid(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAreaid(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setMarriage(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCompany(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setLikeids(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setState(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setCardpic(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setRzstate1(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setRzstate2(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setRzstate3(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setIs_use(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setDateline(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setUserId(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setChannelId(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setDeviceType(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setChooseid(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setAgestart(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setAgeend(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setHeightlstart(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setHeightlend(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setEducationm(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setMarriagem(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setPname(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setCityName(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setIs_push(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Emp entity, long rowId) {
        return entity.getEmpid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Emp entity) {
        if(entity != null) {
            return entity.getEmpid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
