package com.lbins.meetlove.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lbins.meetlove.dao.HappyHandMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HAPPY_HAND_MESSAGE.
*/
public class HappyHandMessageDao extends AbstractDao<HappyHandMessage, String> {

    public static final String TABLENAME = "HAPPY_HAND_MESSAGE";

    /**
     * Properties of entity HappyHandMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Msgid = new Property(0, String.class, "msgid", true, "MSGID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Dateline = new Property(2, String.class, "dateline", false, "DATELINE");
        public final static Property Empid = new Property(3, String.class, "empid", false, "EMPID");
        public final static Property Is_read = new Property(4, String.class, "is_read", false, "IS_READ");
    };

    private DaoSession daoSession;


    public HappyHandMessageDao(DaoConfig config) {
        super(config);
    }
    
    public HappyHandMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HAPPY_HAND_MESSAGE' (" + //
                "'MSGID' TEXT PRIMARY KEY NOT NULL ," + // 0: msgid
                "'TITLE' TEXT," + // 1: title
                "'DATELINE' TEXT," + // 2: dateline
                "'EMPID' TEXT," + // 3: empid
                "'IS_READ' TEXT);"); // 4: is_read
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HAPPY_HAND_MESSAGE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HappyHandMessage entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getMsgid());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String dateline = entity.getDateline();
        if (dateline != null) {
            stmt.bindString(3, dateline);
        }
 
        String empid = entity.getEmpid();
        if (empid != null) {
            stmt.bindString(4, empid);
        }
 
        String is_read = entity.getIs_read();
        if (is_read != null) {
            stmt.bindString(5, is_read);
        }
    }

    @Override
    protected void attachEntity(HappyHandMessage entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HappyHandMessage readEntity(Cursor cursor, int offset) {
        HappyHandMessage entity = new HappyHandMessage( //
            cursor.getString(offset + 0), // msgid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dateline
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // empid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // is_read
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HappyHandMessage entity, int offset) {
        entity.setMsgid(cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDateline(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEmpid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIs_read(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(HappyHandMessage entity, long rowId) {
        return entity.getMsgid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(HappyHandMessage entity) {
        if(entity != null) {
            return entity.getMsgid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
