package com.lbins.meetlove.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lbins.meetlove.dao.HappyHandJw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HAPPY_HAND_JW.
*/
public class HappyHandJwDao extends AbstractDao<HappyHandJw, String> {

    public static final String TABLENAME = "HAPPY_HAND_JW";

    /**
     * Properties of entity HappyHandJw.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Jwid = new Property(0, String.class, "jwid", true, "JWID");
        public final static Property Empid1 = new Property(1, String.class, "empid1", false, "EMPID1");
        public final static Property Empid2 = new Property(2, String.class, "empid2", false, "EMPID2");
        public final static Property Applytime = new Property(3, String.class, "applytime", false, "APPLYTIME");
        public final static Property Startime = new Property(4, String.class, "startime", false, "STARTIME");
        public final static Property Endtime = new Property(5, String.class, "endtime", false, "ENDTIME");
        public final static Property Is_check = new Property(6, String.class, "is_check", false, "IS_CHECK");
        public final static Property Is_use = new Property(7, String.class, "is_use", false, "IS_USE");
        public final static Property Empid1Cover = new Property(8, String.class, "empid1Cover", false, "EMPID1_COVER");
        public final static Property Empid1Nickname = new Property(9, String.class, "empid1Nickname", false, "EMPID1_NICKNAME");
        public final static Property Empid2Cover = new Property(10, String.class, "empid2Cover", false, "EMPID2_COVER");
        public final static Property Empid2Nickname = new Property(11, String.class, "empid2Nickname", false, "EMPID2_NICKNAME");
    };

    private DaoSession daoSession;


    public HappyHandJwDao(DaoConfig config) {
        super(config);
    }
    
    public HappyHandJwDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HAPPY_HAND_JW' (" + //
                "'JWID' TEXT PRIMARY KEY NOT NULL ," + // 0: jwid
                "'EMPID1' TEXT," + // 1: empid1
                "'EMPID2' TEXT," + // 2: empid2
                "'APPLYTIME' TEXT," + // 3: applytime
                "'STARTIME' TEXT," + // 4: startime
                "'ENDTIME' TEXT," + // 5: endtime
                "'IS_CHECK' TEXT," + // 6: is_check
                "'IS_USE' TEXT," + // 7: is_use
                "'EMPID1_COVER' TEXT," + // 8: empid1Cover
                "'EMPID1_NICKNAME' TEXT," + // 9: empid1Nickname
                "'EMPID2_COVER' TEXT," + // 10: empid2Cover
                "'EMPID2_NICKNAME' TEXT);"); // 11: empid2Nickname
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HAPPY_HAND_JW'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HappyHandJw entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getJwid());
 
        String empid1 = entity.getEmpid1();
        if (empid1 != null) {
            stmt.bindString(2, empid1);
        }
 
        String empid2 = entity.getEmpid2();
        if (empid2 != null) {
            stmt.bindString(3, empid2);
        }
 
        String applytime = entity.getApplytime();
        if (applytime != null) {
            stmt.bindString(4, applytime);
        }
 
        String startime = entity.getStartime();
        if (startime != null) {
            stmt.bindString(5, startime);
        }
 
        String endtime = entity.getEndtime();
        if (endtime != null) {
            stmt.bindString(6, endtime);
        }
 
        String is_check = entity.getIs_check();
        if (is_check != null) {
            stmt.bindString(7, is_check);
        }
 
        String is_use = entity.getIs_use();
        if (is_use != null) {
            stmt.bindString(8, is_use);
        }
 
        String empid1Cover = entity.getEmpid1Cover();
        if (empid1Cover != null) {
            stmt.bindString(9, empid1Cover);
        }
 
        String empid1Nickname = entity.getEmpid1Nickname();
        if (empid1Nickname != null) {
            stmt.bindString(10, empid1Nickname);
        }
 
        String empid2Cover = entity.getEmpid2Cover();
        if (empid2Cover != null) {
            stmt.bindString(11, empid2Cover);
        }
 
        String empid2Nickname = entity.getEmpid2Nickname();
        if (empid2Nickname != null) {
            stmt.bindString(12, empid2Nickname);
        }
    }

    @Override
    protected void attachEntity(HappyHandJw entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HappyHandJw readEntity(Cursor cursor, int offset) {
        HappyHandJw entity = new HappyHandJw( //
            cursor.getString(offset + 0), // jwid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // empid1
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // empid2
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // applytime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // startime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // endtime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // is_check
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // is_use
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // empid1Cover
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // empid1Nickname
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // empid2Cover
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // empid2Nickname
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HappyHandJw entity, int offset) {
        entity.setJwid(cursor.getString(offset + 0));
        entity.setEmpid1(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEmpid2(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setApplytime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStartime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEndtime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIs_check(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIs_use(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEmpid1Cover(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEmpid1Nickname(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setEmpid2Cover(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setEmpid2Nickname(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(HappyHandJw entity, long rowId) {
        return entity.getJwid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(HappyHandJw entity) {
        if(entity != null) {
            return entity.getJwid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
